--- #YAML:1.0
name:                File-UStore
version:             0.04
abstract:            Perl extension to store files  on a filesystem using a UUID based storage
license:             perl
author:              
    - Shantanu Bhadoria<shantanu.bhadoria@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    UUID:                          0
    File::Spec:                    0
    File::Copy:                    0
    File::Path:                    0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
